const fs=require('fs'),path=require('path'),d=__dirname;
let h='';
h+='<!DOCTYPE html><html lang=zh-CN><head><meta charset=UTF-8>';
h+='<meta name=viewport content=width=device-width,initial-scale=1.0>';
h+='<title>痘痘皮肤自测诊断</title><link rel=stylesheet href=style.css>';
h+='</head><body><div class=c>';
h+='<div class=hd><h1>痘痘皮肤自测诊断</h1><p>6步找到你的痘痘类型与解决方案</p></div>';
h+='<div class=pb><div class=pb-bar id=pb></div></div><div class=pbl id=pbl>开始测试</div>';
h+='<div class=cd id=intro><div class=in><h2>开始自测</h2>';
h+='<p>回答几个简单问题,系统自动分析你的痘痘类型并给出分阶段护肤方案</p>';
h+='<button class=btn-p id=startBtn>开始答题</button></div></div>';
h+='<div id=stages></div><div class=int id=intercept></div>';
h+='<div class=ld id=loading><div class=sp></div><p>正在分析...</p><div class=ls id=lsteps>分析中</div></div>';
h+='<div id=result></div></div><script src=app.js></script></body></html>';
fs.writeFileSync(path.join(d,'index.html'),h,'utf8');
console.log('HTML: '+h.length);
